[phases.setup]
nixPkgs = ["nodejs_20", "bun", "openssl_3"]

[phases.install]
cmds = ["bun install --no-save"]

[phases.build]
cmds = ["bun run db:generate", "bun run build"]

[start]
cmd = "bun run db:push && bun x prisma db seed && bun run start"
